readable results table
thomaspaenns/EV-placement pull request #7
Opened 2024-03-12 11:08 UTC by YvoneYang

<img width="1702" alt="Screenshot 2024-03-12 at 7 06 02 AM" src="https://github.com/thomaspaenns/EV-placement/assets/61671446/60f418b4-bc54-44b4-9616-ccfdfbfc4955">

Added a table with information on selected stations and individual station KPIs on the results page

2024-03-12 15:49 UTC, thomaspaenns requested changes
Looks good overall, a few very small changes but should only take 10ish minutes to implement

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
When I boot up the app I get this error:
![image](https://github.com/thomaspaenns/EV-placement/assets/57325103/7eb391a9-50b7-4ea3-9ef8-f87620a366b3)
Might want to change the import - I requested the change on that specific line

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
> +import dash_table
```suggestion

```
Can just be added to line 4

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
>  from dash import dcc, html, callback, Input, Output
```suggestion
from dash import dcc, html, callback, dash_table, Input, Output
```
Import convention (should fix error)

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
> +        dcc.Graph(id='coverage-map'),
Can you add some whitespace between the map and the table? Perhaps a title as well (Station Stats or something)

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
> +        export_df = export_df[export_df['Util']>0]
Can you drop the coverage column from the table (It's kinda pointless cause the coverage will always be at or near 100% in the segments where there is a station)

2024-03-12 15:49 UTC, thomaspaenns commented on pages/results.py
>      ], style={'marginLeft': '20px', 'marginRight': '20px'})
Can you also add some whitespace below the table? (you can just use marginTop and marginBottom within the style dictionary)

2024-03-13 14:15 UTC, thomaspaenns approved these changes
LGTM!

2024-03-13 14:24 UTC, z22shaik approved these changes
LGTM

2024-03-13 14:25 UTC, merged